"use client";
import {useEffect,useMemo,useState} from "react";
import GeoMap from "@/components/GeoMap";
import {expandirBanca,expandirEscuela,expandirSalud,type Banca,type BancasPayload,type Escuela,type EscuelasPayload,type Salud,type SaludPayload} from "@/lib/sample-data";
const ALL="Todos", SCHOOL_LIMIT=200, HEALTH_LIMIT=200;
const distance=(a:{lat:number;lng:number},b:{lat:number;lng:number})=>{const r=6371000,rad=(v:number)=>v*Math.PI/180,dlat=rad(b.lat-a.lat),dlng=rad(b.lng-a.lng),x=Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlng/2)**2;return r*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};
const fmt=(m:number)=>m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(2)} km`;
function nearest<T extends {lat:number;lng:number}>(p:{lat:number;lng:number},items:T[]){let item:T|undefined,d=Infinity;for(const x of items){const n=distance(p,x);if(n<d){d=n;item=x}}return {item,d}}
type Sim={point:{lat:number;lng:number};school?:Escuela;schoolD:number;health?:Salud;healthD:number};
type SelectedBanca=Banca&{saludCercana?:Salud;saludDistanciaM:number};
type AnalysisTarget={id:string;type:"escuela"|"salud";name:string;lat:number;lng:number;color:string};
export default function Home(){
 const [bancas,setBancas]=useState<Banca[]>([]),[escuelas,setEscuelas]=useState<Escuela[]>([]),[salud,setSalud]=useState<Salud[]>([]);const [meta,setMeta]=useState({total:0,mapped:0,pending:0}),[schoolMeta,setSchoolMeta]=useState({mapped:0,source:""}),[healthMeta,setHealthMeta]=useState({mapped:0,source:""});
 const [query,setQuery]=useState(""),[province,setProvince]=useState(ALL),[status,setStatus]=useState(ALL),[risk,setRisk]=useState(ALL);const [showBancas,setShowBancas]=useState(true),[showSchools,setShowSchools]=useState(true),[showHealth,setShowHealth]=useState(true),[showLines,setShowLines]=useState(true),[showStats,setShowStats]=useState(true),[showDetails,setShowDetails]=useState(true),[showStatus,setShowStatus]=useState(true),[panel,setPanel]=useState(true),[viewMenu,setViewMenu]=useState(false),[cleanMode,setCleanMode]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [selected,setSelected]=useState<SelectedBanca|null>(null),[selectedSchool,setSelectedSchool]=useState<Escuela|null>(null),[selectedHealth,setSelectedHealth]=useState<Salud|null>(null);const [simMode,setSimMode]=useState(false),[sim,setSim]=useState<Sim|null>(null);
 useEffect(()=>{const json=<T,>(url:string)=>fetch(url,{cache:"force-cache"}).then(async r=>{if(!r.ok)throw new Error(`${url}: ${r.status}`);return await r.json() as T});Promise.all([json<BancasPayload>("/data/bancas.json"),json<EscuelasPayload>("/data/escuelas.json"),json<SaludPayload>("/data/salud.json")]).then(([b,e,s])=>{setBancas(b.records.map(expandirBanca));setEscuelas(e.records.map(expandirEscuela));setSalud(s.records.map(expandirSalud));setMeta(b.meta);setSchoolMeta(e.meta);setHealthMeta(s.meta);setLoading(false)}).catch(()=>{setError("No fue posible cargar las capas geográficas");setLoading(false)})},[]);
 const provinces=useMemo(()=>[ALL,...Array.from(new Set(bancas.map(b=>b.provincia))).sort()],[bancas]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return bancas.filter(b=>(!q||[b.id,b.nombre,b.propietario,b.provincia,b.municipio,b.sector,b.direccion].some(v=>v.toLowerCase().includes(q)))&&(province===ALL||b.provincia===province)&&(status===ALL||b.estatus===status)&&(risk===ALL||b.riesgo===risk))},[bancas,query,province,status,risk]);
 const schools=useMemo(()=>province===ALL?escuelas:escuelas.filter(x=>x.provincia===province),[escuelas,province]), health=useMemo(()=>province===ALL?salud:salud.filter(x=>x.provincia===province),[salud,province]);
 const chooseBanca=(b:Banca)=>{const school=nearest(b,escuelas),healthCenter=nearest(b,salud);setSelected({...b,escuelaCercanaCodigo:school.item?.codigo||"",escuelaCercanaNombre:school.item?.nombre||"",escuelaDistanciaM:school.d,escuelaLat:school.item?.lat||0,escuelaLng:school.item?.lng||0,saludCercana:healthCenter.item,saludDistanciaM:healthCenter.d});setSelectedSchool(null);setSelectedHealth(null);setSim(null);setShowSchools(true);setShowHealth(true)};
 const simulate=(point:{lat:number;lng:number})=>{const a=nearest(point,escuelas),h=nearest(point,salud);setSim({point,school:a.item,schoolD:a.d,health:h.item,healthD:h.d});setSelected(null);setSelectedSchool(null);setSelectedHealth(null);setShowSchools(true);setShowHealth(true)};
 const closeCards=()=>{setSelected(null);setSelectedSchool(null);setSelectedHealth(null);setSim(null)};
 const toggleCleanMode=()=>{setCleanMode(v=>!v);setViewMenu(false)};
 const analysisOrigin=selected?{lat:selected.lat,lng:selected.lng}:sim?.point||null;
 const analysisTargets=useMemo<AnalysisTarget[]>(()=>{
  if(selected){const targets:AnalysisTarget[]=[];if(selected.escuelaLat&&selected.escuelaLng)targets.push({id:selected.escuelaCercanaCodigo,type:"escuela",name:selected.escuelaCercanaNombre,lat:selected.escuelaLat,lng:selected.escuelaLng,color:"#8b5cf6"});if(selected.saludCercana)targets.push({id:selected.saludCercana.id,type:"salud",name:selected.saludCercana.nombre,lat:selected.saludCercana.lat,lng:selected.saludCercana.lng,color:"#22c9f4"});return targets}
  if(sim){const targets:AnalysisTarget[]=[];if(sim.school)targets.push({id:sim.school.codigo,type:"escuela",name:sim.school.nombre,lat:sim.school.lat,lng:sim.school.lng,color:"#8b5cf6"});if(sim.health)targets.push({id:sim.health.id,type:"salud",name:sim.health.nombre,lat:sim.health.lat,lng:sim.health.lng,color:"#22c9f4"});return targets}
  return [];
 },[selected,sim]);
 return <main className="app-shell">
  <header className="app-header"><div className="brand-lockup"><div className="brand-mark">GB</div><div><strong>GeoBancas RD</strong><span>Inteligencia territorial y cumplimiento</span></div></div><div className="header-actions"><button className="ghost-button desktop-only">Exportar</button><button className={`primary-button ${simMode?"active-mode":""}`} onClick={()=>{setSimMode(v=>!v);closeCards()}}>{simMode?"Salir del simulador":"Simular ubicación"}</button><div className="user-chip"><span>MP</span><div><strong>Miguel Paulino</strong><small>Administrador</small></div></div></div></header>
  <section className="map-workspace">
   <GeoMap data={filtered} escuelas={schools} salud={health} showBancas={showBancas} showEscuelas={showSchools} showSalud={showHealth} showAnalysisLines={showLines&&!cleanMode} selectedId={selected?.id} selectedEscuelaCodigo={selectedSchool?.codigo} selectedSaludId={selectedHealth?.id} simulationMode={simMode} simulationPoint={sim?.point} analysisOrigin={analysisOrigin} analysisTargets={analysisTargets} onSimulationPoint={simulate} onSelect={chooseBanca} onSelectEscuela={x=>{setSelectedSchool(x);setSelected(null);setSelectedHealth(null);setSim(null)}} onSelectSalud={x=>{setSelectedHealth(x);setSelected(null);setSelectedSchool(null);setSim(null)}}/>
   {(loading||error)&&<div className={`data-state ${error?"error":""}`}><span className="loader"/><div><strong>{error||"Cargando plataforma territorial"}</strong><small>{error?"Revisa los archivos públicos.":"Preparando bancas, escuelas y centros de salud…"}</small></div></div>}
   {simMode&&!sim&&<div className="sim-hint"><strong>Simulador de viabilidad</strong><span>Toca cualquier punto del mapa para analizar el local.</span></div>}
   <div className="floating-tools" role="toolbar" aria-label="Controles de visualización"><button className={`floating-tool ${panel&&!cleanMode?"primary":""}`} onClick={()=>{setCleanMode(false);setPanel(v=>!v);setViewMenu(false)}} title="Mostrar u ocultar control geográfico" aria-pressed={panel&&!cleanMode}>☰</button><button className={`floating-tool ${viewMenu?"active":""}`} onClick={()=>{setCleanMode(false);setViewMenu(v=>!v)}} title="Opciones de visualización" aria-pressed={viewMenu}>◫</button><button className={`floating-tool ${cleanMode?"active":""}`} onClick={toggleCleanMode} title={cleanMode?"Restaurar interfaz":"Ver mapa sin distracciones"} aria-pressed={cleanMode}>{cleanMode?"↺":"⛶"}</button></div><button className="mobile-filter-button" onClick={()=>{setCleanMode(false);setPanel(true)}}>☰ Filtros y capas</button>
   <aside className={`control-panel ${panel&&!cleanMode?"panel-open mobile-open":"panel-closed"}`}><div className="panel-head"><div><span className="eyebrow">Control geográfico</span><h1>Mapa nacional</h1></div><button className="icon-button" onClick={()=>setPanel(false)}>×</button></div>
    <label className="search-box"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar banca, propietario o ubicación"/></label>
    <div className="filter-grid"><label><span>Provincia</span><select value={province} onChange={e=>setProvince(e.target.value)}>{provinces.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Estatus</span><select value={status} onChange={e=>setStatus(e.target.value)}><option>Todos</option><option>Legal</option><option>Ilegal</option><option>Pendiente</option><option>Suspendida</option></select></label><label><span>Riesgo</span><select value={risk} onChange={e=>setRisk(e.target.value)}><option>Todos</option><option>Bajo</option><option>Moderado</option><option>Alto</option></select></label></div>
    <div className="layers-title">Capas territoriales</div><Layer title="Bancas de lotería" count={filtered.length} active={showBancas} color="banca" onClick={()=>setShowBancas(v=>!v)}/><Layer title="Centros educativos" count={schools.length} active={showSchools} color="school" onClick={()=>setShowSchools(v=>!v)}/><Layer title="Centros de salud" count={health.length} active={showHealth} color="health" onClick={()=>setShowHealth(v=>!v)}/>
    <div className="filter-footer"><strong>{filtered.length.toLocaleString("es-DO")} bancas visibles</strong><button onClick={()=>{setQuery("");setProvince(ALL);setStatus(ALL);setRisk(ALL)}}>Limpiar</button></div>
   </aside>
   {panel&&!cleanMode&&<div className="mobile-overlay" onClick={()=>setPanel(false)}/>}
   {viewMenu&&!cleanMode&&<section className="view-menu"><div className="view-menu-head"><div><span className="eyebrow">Visualización</span><strong>Elementos del mapa</strong></div><button onClick={()=>setViewMenu(false)}>×</button></div><ViewToggle label="Bancas" active={showBancas} onClick={()=>setShowBancas(v=>!v)}/><ViewToggle label="Escuelas" active={showSchools} onClick={()=>setShowSchools(v=>!v)}/><ViewToggle label="Centros de salud" active={showHealth} onClick={()=>setShowHealth(v=>!v)}/><ViewToggle label="Líneas de proximidad" active={showLines} onClick={()=>setShowLines(v=>!v)}/><ViewToggle label="Indicadores superiores" active={showStats} onClick={()=>setShowStats(v=>!v)}/><ViewToggle label="Ficha de detalle" active={showDetails} onClick={()=>setShowDetails(v=>!v)}/><ViewToggle label="Estado inferior" active={showStatus} onClick={()=>setShowStatus(v=>!v)}/><ViewToggle label="Panel de control" active={panel} onClick={()=>setPanel(v=>!v)}/><button className="clean-map-button" onClick={toggleCleanMode}>Ver mapa sin distracciones</button></section>} 
   {showStats&&!cleanMode&&<section className="map-stats"><article><span>Bancas ubicadas</span><strong>{meta.mapped.toLocaleString("es-DO")}</strong></article><article><span>Escuelas</span><strong>{schoolMeta.mapped.toLocaleString("es-DO")}</strong></article><article><span>Salud</span><strong>{healthMeta.mapped.toLocaleString("es-DO")}</strong></article><article><span>Por validar</span><strong>{meta.pending.toLocaleString("es-DO")}</strong></article></section>}
   {selected&&showDetails&&!cleanMode&&<Detail title={selected.nombre} code={selected.id} onClose={()=>setSelected(null)}><div className="status-row"><span className={`status-badge ${selected.estatus.toLowerCase()}`}>{selected.estatus}</span><span className={`risk-badge ${selected.riesgo.toLowerCase()}`}>Riesgo {selected.riesgo}</span></div><dl><div><dt>Propietario</dt><dd>{selected.propietario}</dd></div><div><dt>Ubicación</dt><dd>{selected.sector}, {selected.municipio}</dd></div><div><dt>Dirección</dt><dd>{selected.direccion}</dd></div><div><dt>Coordenadas</dt><dd>{selected.lat.toFixed(6)}, {selected.lng.toFixed(6)}</dd></div></dl><Compliance label="Escuela más cercana" name={selected.escuelaCercanaNombre||"No identificada"} meters={selected.escuelaDistanciaM} limit={SCHOOL_LIMIT}/><Compliance label="Centro de salud más cercano" name={selected.saludCercana?.nombre||"No identificado"} meters={selected.saludDistanciaM} limit={HEALTH_LIMIT}/><div className="detail-actions"><button>Ver expediente</button><button className="primary-button">Iniciar inspección</button></div></Detail>}
   {selectedSchool&&showDetails&&!cleanMode&&<Detail title={selectedSchool.nombre} code={`CENTRO ${selectedSchool.codigo}`} onClose={()=>setSelectedSchool(null)}><span className="school-badge">Centro educativo</span><dl><div><dt>Provincia</dt><dd>{selectedSchool.provincia}</dd></div><div><dt>Municipio</dt><dd>{selectedSchool.municipio}</dd></div><div><dt>Nivel</dt><dd>{selectedSchool.nivel}</dd></div><div><dt>Sector</dt><dd>{selectedSchool.sector}</dd></div></dl><Source text={schoolMeta.source}/></Detail>}
   {selectedHealth&&showDetails&&!cleanMode&&<Detail title={selectedHealth.nombre} code={`SALUD ${selectedHealth.id}`} onClose={()=>setSelectedHealth(null)}><span className="health-badge">{selectedHealth.tipo}</span><dl><div><dt>Provincia</dt><dd>{selectedHealth.provincia}</dd></div><div><dt>Municipio</dt><dd>{selectedHealth.municipio}</dd></div><div><dt>Nivel</dt><dd>{selectedHealth.nivel}</dd></div><div><dt>Estado</dt><dd>{selectedHealth.estado}</dd></div><div><dt>Dirección</dt><dd>{selectedHealth.direccion}</dd></div></dl><Source text={healthMeta.source}/></Detail>}
   {sim&&showDetails&&!cleanMode&&<Detail title="Análisis del local" code="SIMULADOR TERRITORIAL" onClose={()=>setSim(null)}><div className={`viability ${sim.schoolD>=SCHOOL_LIMIT&&sim.healthD>=HEALTH_LIMIT?"ok":"alert"}`}><strong>{sim.schoolD>=SCHOOL_LIMIT&&sim.healthD>=HEALTH_LIMIT?"Ubicación preliminarmente viable":"Ubicación no recomendada"}</strong><span>Evaluación automática con las capas disponibles.</span></div><Compliance label="Centro educativo" name={sim.school?.nombre||"No identificado"} meters={sim.schoolD} limit={SCHOOL_LIMIT}/><Compliance label="Centro de salud" name={sim.health?.nombre||"No identificado"} meters={sim.healthD} limit={HEALTH_LIMIT}/><small className="legal-note">Resultado preliminar. Requiere medición oficial, validación de coordenadas y revisión de la norma aplicable.</small><button className="full-button" onClick={()=>setSimMode(true)}>Analizar otro punto</button></Detail>}
   <nav className="mobile-nav"><button onClick={()=>setPanel(true)}>☰<span>Filtros</span></button><button className={simMode?"active":""} onClick={()=>{setSimMode(v=>!v);closeCards()}}>◎<span>Simular</span></button><button onClick={()=>{setShowSchools(v=>!v)}}>▣<span>Escuelas</span></button><button onClick={()=>setShowHealth(v=>!v)}>✚<span>Salud</span></button></nav>
   {showStatus&&!cleanMode&&<div className="map-status"><span className="pulse"/>Mapa conectado · {filtered.length.toLocaleString("es-DO")} bancas</div>}
  </section>
 </main>
}
function Layer({title,count,active,color,onClick}:{title:string;count:number;active:boolean;color:string;onClick:()=>void}){return <div className="layer-switch"><div><i className={`layer-dot ${color}`}/><strong>{title}</strong><small>{count.toLocaleString("es-DO")} ubicaciones</small></div><button className={active?"active":""} onClick={onClick}><span/></button></div>}
function Detail({title,code,onClose,children}:{title:string;code:string;onClose:()=>void;children:React.ReactNode}){return <aside className="detail-card"><div className="detail-handle"/><div className="detail-top"><div><span className="record-code">{code}</span><h2>{title}</h2></div><button onClick={onClose}>×</button></div>{children}</aside>}
function Compliance({label,name,meters,limit}:{label:string;name:string;meters:number;limit:number}){const ok=meters>=limit;return <div className="proximity-box"><span>{label}</span><strong>{name}</strong><div className="distance-value">{fmt(meters)}</div><div className={`compliance-result ${ok?"ok":"alert"}`}><b>{ok?"Fuera del radio restringido":"Posible incumplimiento"}</b><em>Referencia activa: mínimo {limit} m lineales</em><small>{ok?`Supera la referencia por ${Math.floor(meters-limit)} m.`:`Faltan aproximadamente ${Math.ceil(limit-meters)} m.`}</small></div></div>}

function ViewToggle({label,active,onClick}:{label:string;active:boolean;onClick:()=>void}){return <button className="view-toggle" onClick={onClick}><span>{label}</span><i className={active?"active":""}><b/></i></button>}
function Source({text}:{text:string}){return <div className="proximity-box"><span>Fuente de datos</span><strong>{text}</strong><small>Registro geográfico suministrado e integrado a la plataforma.</small></div>}
