"use client";
import {useEffect,useMemo,useState} from "react";
import GeoMap from "@/components/GeoMap";
import {expandirBanca,expandirEscuela,expandirSalud,expandirDestacamento,type Banca,type BancasPayload,type Escuela,type EscuelasPayload,type Salud,type SaludPayload,type Destacamento,type DestacamentosPayload} from "@/lib/sample-data";
const ALL="Todos", PROTECTED_PLACE_LIMIT=500, LOTTERY_BANK_LIMIT=200;
const distance=(a:{lat:number;lng:number},b:{lat:number;lng:number})=>{const r=6371000,rad=(v:number)=>v*Math.PI/180,dlat=rad(b.lat-a.lat),dlng=rad(b.lng-a.lng),x=Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlng/2)**2;return r*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};
const fmt=(m:number)=>m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(2)} km`;
function nearest<T extends {lat:number;lng:number}>(p:{lat:number;lng:number},items:T[]){let item:T|undefined,d=Infinity;for(const x of items){const n=distance(p,x);if(n<d){d=n;item=x}}return {item,d}}
const RD_POLYGON:[number,number][]=[[-71.712361,19.714456],[-71.587304,19.884911],[-70.806706,19.880286],[-70.214365,19.622885],[-69.950815,19.648],[-69.76925,19.293267],[-69.222126,19.313214],[-69.254346,19.015196],[-68.809412,18.979074],[-68.317943,18.612198],[-68.689316,18.205142],[-69.164946,18.422648],[-69.623988,18.380713],[-69.952934,18.428307],[-70.133233,18.245915],[-70.517137,18.184291],[-70.669298,18.426886],[-70.99995,18.283329],[-71.40021,17.598564],[-71.657662,17.757573],[-71.708305,18.044997],[-71.687738,18.31666],[-71.945112,18.6169],[-71.701303,18.785417],[-71.624873,19.169838],[-71.712361,19.714456]];
const pointInPolygon=(lng:number,lat:number,polygon:[number,number][])=>{let inside=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const [xi,yi]=polygon[i],[xj,yj]=polygon[j];const hit=((yi>lat)!==(yj>lat))&&(lng<(xj-xi)*(lat-yi)/(yj-yi)+xi);if(hit)inside=!inside}return inside};
const inBroadRDBounds=(b:{lat:number;lng:number})=>Number.isFinite(b.lat)&&Number.isFinite(b.lng)&&b.lat>=17.45&&b.lat<=20.05&&b.lng>=-72.05&&b.lng<=-68.20;
const norm=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const medianPoint=(items:Banca[])=>{const lats=items.map(x=>x.lat).sort((a,b)=>a-b),lngs=items.map(x=>x.lng).sort((a,b)=>a-b),m=Math.floor(items.length/2);return {lat:lats[m],lng:lngs[m]}};
function repairBancaLocations(items:Banca[]){
 const allGroups=new Map<string,Banca[]>();for(const b of items){if(!inBroadRDBounds(b))continue;const k=`${norm(b.municipio)}|${norm(b.provincia)}`;const arr=allGroups.get(k)||[];arr.push(b);allGroups.set(k,arr)}
 const localityCenters=new Map<string,{lat:number;lng:number}>();for(const [k,v] of allGroups)localityCenters.set(k,medianPoint(v));
 const isSuspect=(b:Banca)=>{if(!inBroadRDBounds(b))return true;if(pointInPolygon(b.lng,b.lat,RD_POLYGON))return false;const center=localityCenters.get(`${norm(b.municipio)}|${norm(b.provincia)}`);return center?distance(b,center)>8000:true};
 const valid=items.filter(b=>!isSuspect(b));const groups=(key:(b:Banca)=>string)=>{const map=new Map<string,Banca[]>();for(const b of valid){const k=key(b);if(!k)continue;const arr=map.get(k)||[];arr.push(b);map.set(k,arr)}return map};
 const byAddress=groups(b=>`${norm(b.direccion)}|${norm(b.municipio)}|${norm(b.provincia)}`),bySector=groups(b=>`${norm(b.sector)}|${norm(b.municipio)}|${norm(b.provincia)}`),byMunicipio=groups(b=>`${norm(b.municipio)}|${norm(b.provincia)}`),byProvincia=groups(b=>norm(b.provincia));
 let corrected=0,pending=0;
 const records=items.map(b=>{if(!isSuspect(b))return {...b,locationSource:"original" as const};const originalLat=b.lat,originalLng=b.lng;const candidates:[Map<string,Banca[]>,string,Banca["locationSource"],number][]=[
  [byAddress,`${norm(b.direccion)}|${norm(b.municipio)}|${norm(b.provincia)}`,"direccion",1],
  [bySector,`${norm(b.sector)}|${norm(b.municipio)}|${norm(b.provincia)}`,"sector",2],
  [byMunicipio,`${norm(b.municipio)}|${norm(b.provincia)}`,"municipio",3],
  [byProvincia,norm(b.provincia),"provincia",8]
 ];
 for(const [map,key,source,min] of candidates){const matches=map.get(key);if(matches&&matches.length>=min){const p=medianPoint(matches);corrected++;return {...b,...p,originalLat,originalLng,locationSource:source}}}
 pending++;return {...b,originalLat,originalLng,locationSource:"pendiente" as const}
 });return {records,corrected,pending};
}
type Sim={point:{lat:number;lng:number};school?:Escuela;schoolD:number;health?:Salud;healthD:number;police?:Destacamento;policeD:number};
type SelectedBanca=Banca&{saludCercana?:Salud;saludDistanciaM:number;destacamentoCercano?:Destacamento;destacamentoDistanciaM:number;nearbyBancas:{banca:Banca;distanceM:number}[]};
type AnalysisTarget={id:string;type:"escuela"|"salud"|"destacamento"|"banca";name:string;lat:number;lng:number;color:string};

function countNearbyEntities<T extends {lat:number;lng:number}>(banks:Banca[],entities:T[],radius=PROTECTED_PLACE_LIMIT){
 if(!banks.length||!entities.length)return 0;
 const cell=radius/111320;
 const grid=new Map<string,Banca[]>();
 for(const b of banks){const key=`${Math.floor(b.lat/cell)}|${Math.floor(b.lng/cell)}`;const list=grid.get(key)||[];list.push(b);grid.set(key,list)}
 let count=0;
 for(const entity of entities){const y=Math.floor(entity.lat/cell),x=Math.floor(entity.lng/cell);let found=false;for(let dy=-1;dy<=1&&!found;dy++)for(let dx=-1;dx<=1&&!found;dx++){for(const bank of grid.get(`${y+dy}|${x+dx}`)||[]){if(distance(bank,entity)<=radius){found=true;break}}}if(found)count++}
 return count;
}
export default function Home(){
 const [bancas,setBancas]=useState<Banca[]>([]),[escuelas,setEscuelas]=useState<Escuela[]>([]),[salud,setSalud]=useState<Salud[]>([]),[destacamentos,setDestacamentos]=useState<Destacamento[]>([]);const [meta,setMeta]=useState({total:0,mapped:0,pending:0}),[schoolMeta,setSchoolMeta]=useState({mapped:0,source:""}),[healthMeta,setHealthMeta]=useState({mapped:0,source:""}),[policeMeta,setPoliceMeta]=useState({mapped:0,source:""});
 const [query,setQuery]=useState(""),[searchSubmitted,setSearchSubmitted]=useState(false),[province,setProvince]=useState(ALL),[status,setStatus]=useState(ALL),[risk,setRisk]=useState(ALL);const [showBancas,setShowBancas]=useState(true),[showSchools,setShowSchools]=useState(false),[showHealth,setShowHealth]=useState(false),[showPolice,setShowPolice]=useState(false),[showLines,setShowLines]=useState(true),[showStats,setShowStats]=useState(true),[showDetails,setShowDetails]=useState(true),[showStatus,setShowStatus]=useState(true),[panel,setPanel]=useState(true),[viewMenu,setViewMenu]=useState(false),[cleanMode,setCleanMode]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [selected,setSelected]=useState<SelectedBanca|null>(null),[selectedSchool,setSelectedSchool]=useState<Escuela|null>(null),[selectedHealth,setSelectedHealth]=useState<Salud|null>(null),[selectedPolice,setSelectedPolice]=useState<Destacamento|null>(null);const [simMode,setSimMode]=useState(false),[sim,setSim]=useState<Sim|null>(null);const [measureMode,setMeasureMode]=useState(false),[measureA,setMeasureA]=useState<Banca|null>(null),[measureB,setMeasureB]=useState<Banca|null>(null),[locationStats,setLocationStats]=useState({corrected:0,pending:0});
 useEffect(()=>{const json=<T,>(url:string)=>fetch(url,{cache:"force-cache"}).then(async r=>{if(!r.ok)throw new Error(`${url}: ${r.status}`);return await r.json() as T});Promise.all([json<BancasPayload>("/data/bancas.json"),json<EscuelasPayload>("/data/escuelas.json"),json<SaludPayload>("/data/salud.json"),json<DestacamentosPayload>("/data/destacamentos.json")]).then(([b,e,s,d])=>{const repaired=repairBancaLocations(b.records.map(expandirBanca));setBancas(repaired.records);setLocationStats({corrected:repaired.corrected,pending:repaired.pending});setEscuelas(e.records.map(expandirEscuela));setSalud(s.records.map(expandirSalud));setDestacamentos(d.records.map(expandirDestacamento));setMeta(b.meta);setSchoolMeta(e.meta);setHealthMeta(s.meta);setPoliceMeta(d.meta);setLoading(false)}).catch(()=>{setError("No fue posible cargar las capas geográficas");setLoading(false)})},[]);
 const provinces=useMemo(()=>[ALL,...Array.from(new Set(bancas.map(b=>b.provincia))).sort()],[bancas]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return bancas.filter(b=>(!q||[b.id,b.nombre,b.propietario,b.provincia,b.municipio,b.sector,b.direccion].some(v=>v.toLowerCase().includes(q)))&&(province===ALL||b.provincia===province)&&(status===ALL||b.estatus===status)&&(risk===ALL||b.riesgo===risk))},[bancas,query,province,status,risk]);
 const schools=useMemo(()=>province===ALL?escuelas:escuelas.filter(x=>x.provincia===province),[escuelas,province]), health=useMemo(()=>province===ALL?salud:salud.filter(x=>x.provincia===province),[salud,province]), police=destacamentos;
 const filteredStats=useMemo(()=>({total:filtered.length,legal:filtered.filter(x=>x.estatus==="Legal").length,ilegal:filtered.filter(x=>x.estatus==="Ilegal").length,schools:countNearbyEntities(filtered,schools),health:countNearbyEntities(filtered,health),police:countNearbyEntities(filtered,police)}),[filtered,schools,health,police]);
 const hasActiveFilters=query.trim().length>0||province!==ALL||status!==ALL||risk!==ALL;
 useEffect(()=>{if(!query.trim())setSearchSubmitted(false)},[query]);
 const chooseBanca=(b:Banca)=>{if(measureMode){if(!measureA||measureB){setMeasureA(b);setMeasureB(null)}else if(measureA.id!==b.id){setMeasureB(b)}return}const school=nearest(b,escuelas),healthCenter=nearest(b,salud),policeCenter=nearest(b,destacamentos);const nearbyBancas=bancas.filter(x=>x.id!==b.id).map(x=>({banca:x,distanceM:distance(b,x)})).filter(x=>x.distanceM<LOTTERY_BANK_LIMIT).sort((a,c)=>a.distanceM-c.distanceM);setSelected({...b,escuelaCercanaCodigo:school.item?.codigo||"",escuelaCercanaNombre:school.item?.nombre||"",escuelaDistanciaM:school.d,escuelaLat:school.item?.lat||0,escuelaLng:school.item?.lng||0,saludCercana:healthCenter.item,saludDistanciaM:healthCenter.d,destacamentoCercano:policeCenter.item,destacamentoDistanciaM:policeCenter.d,nearbyBancas});setSelectedSchool(null);setSelectedHealth(null);setSelectedPolice(null);setSim(null);setShowSchools(true);setShowHealth(true);setShowPolice(true)};
 const simulate=(point:{lat:number;lng:number})=>{const a=nearest(point,escuelas),h=nearest(point,salud),p=nearest(point,destacamentos);setSim({point,school:a.item,schoolD:a.d,health:h.item,healthD:h.d,police:p.item,policeD:p.d});setSelected(null);setSelectedSchool(null);setSelectedHealth(null);setSelectedPolice(null);setShowSchools(true);setShowHealth(true);setShowPolice(true)};
 const closeCards=()=>{setSelected(null);setSelectedSchool(null);setSelectedHealth(null);setSelectedPolice(null);setSim(null)};
 const openSchool=(x?:Escuela)=>{if(!x)return;setSelectedSchool(x);setSelected(null);setSelectedHealth(null);setSelectedPolice(null);setSim(null)};
 const openHealth=(x?:Salud)=>{if(!x)return;setSelectedHealth(x);setSelected(null);setSelectedSchool(null);setSelectedPolice(null);setSim(null)};
 const openPolice=(x?:Destacamento)=>{if(!x)return;setSelectedPolice(x);setSelected(null);setSelectedSchool(null);setSelectedHealth(null);setSim(null)};
 const toggleMeasure=()=>{setMeasureMode(v=>{const next=!v;if(next){setSimMode(false);closeCards()}else{setMeasureA(null);setMeasureB(null)}return next})};
 const measureDistance=measureA&&measureB?distance(measureA,measureB):null;
 const toggleCleanMode=()=>{setCleanMode(v=>!v);setViewMenu(false)};
 const analysisOrigin=selected?{lat:selected.lat,lng:selected.lng}:sim?.point||null;
 const analysisTargets=useMemo<AnalysisTarget[]>(()=>{
  if(selected){const targets:AnalysisTarget[]=[];if(selected.escuelaLat&&selected.escuelaLng)targets.push({id:selected.escuelaCercanaCodigo,type:"escuela",name:selected.escuelaCercanaNombre,lat:selected.escuelaLat,lng:selected.escuelaLng,color:"#8b5cf6"});if(selected.saludCercana)targets.push({id:selected.saludCercana.id,type:"salud",name:selected.saludCercana.nombre,lat:selected.saludCercana.lat,lng:selected.saludCercana.lng,color:"#22c9f4"});if(selected.destacamentoCercano)targets.push({id:selected.destacamentoCercano.id,type:"destacamento",name:selected.destacamentoCercano.nombre,lat:selected.destacamentoCercano.lat,lng:selected.destacamentoCercano.lng,color:"#f59e0b"});for(const x of selected.nearbyBancas)targets.push({id:x.banca.id,type:"banca",name:x.banca.nombre,lat:x.banca.lat,lng:x.banca.lng,color:"#ff5c73"});return targets}
  if(sim){const targets:AnalysisTarget[]=[];if(sim.school)targets.push({id:sim.school.codigo,type:"escuela",name:sim.school.nombre,lat:sim.school.lat,lng:sim.school.lng,color:"#8b5cf6"});if(sim.health)targets.push({id:sim.health.id,type:"salud",name:sim.health.nombre,lat:sim.health.lat,lng:sim.health.lng,color:"#22c9f4"});if(sim.police)targets.push({id:sim.police.id,type:"destacamento",name:sim.police.nombre,lat:sim.police.lat,lng:sim.police.lng,color:"#f59e0b"});return targets}
  return [];
 },[selected,sim]);
 return <main className="app-shell">
  <header className="app-header"><div className="brand-lockup"><div className="brand-mark">GB</div><div><strong>GeoBancas RD</strong><span>Inteligencia territorial y cumplimiento</span></div></div><div className="header-actions"><button className="ghost-button desktop-only">Exportar</button><button className={`ghost-button ${measureMode?"active-measure":""}`} onClick={toggleMeasure}>{measureMode?"Salir de medición":"Medir bancas"}</button><button className={`primary-button ${simMode?"active-mode":""}`} onClick={()=>{setMeasureMode(false);setMeasureA(null);setMeasureB(null);setSimMode(v=>!v);closeCards()}}>{simMode?"Salir del simulador":"Simular ubicación"}</button><div className="user-chip"><span>MP</span><div><strong>Miguel Paulino</strong><small>Administrador</small></div></div></div></header>
  <section className="map-workspace">
   <GeoMap revealFiltered={searchSubmitted&&hasActiveFilters} measureMode={measureMode} measureSelection={{a:measureA,b:measureB}} data={filtered} escuelas={schools} salud={health} destacamentos={police} showBancas={showBancas} showEscuelas={showSchools} showSalud={showHealth} showDestacamentos={showPolice} showAnalysisLines={showLines&&!cleanMode} selectedId={selected?.id} selectedEscuelaCodigo={selectedSchool?.codigo} selectedSaludId={selectedHealth?.id} selectedDestacamentoId={selectedPolice?.id} simulationMode={simMode} simulationPoint={sim?.point} analysisOrigin={analysisOrigin} analysisTargets={analysisTargets} onSimulationPoint={simulate} onSelect={chooseBanca} onSelectEscuela={openSchool} onSelectSalud={openHealth} onSelectDestacamento={openPolice}/>
   {(loading||error)&&<div className={`data-state ${error?"error":""}`}><span className="loader"/><div><strong>{error||"Cargando plataforma territorial"}</strong><small>{error?"Revisa los archivos públicos.":"Preparando bancas, escuelas y centros de salud…"}</small></div></div>}
   {simMode&&!sim&&<div className="sim-hint"><strong>Simulador de viabilidad</strong><span>Toca cualquier punto del mapa para analizar el local.</span></div>}
   {measureMode&&!measureB&&<div className="measure-hint"><strong>{measureA?"Selecciona la segunda banca":"Selecciona la primera banca"}</strong><span>Puedes combinar una banca legal, ilegal, pendiente o suspendida.</span></div>}
   {measureA&&measureB&&!cleanMode&&<aside className="measure-card"><div className="measure-card-head"><div><span className="eyebrow">Medición lineal</span><strong>Distancia entre bancas</strong></div><button onClick={()=>{setMeasureA(null);setMeasureB(null)}}>×</button></div><MeasureBank label="A" banca={measureA}/><div className="measure-distance">{fmt(measureDistance||0)}</div><div className={`measure-compliance ${(measureDistance||0)>=LOTTERY_BANK_LIMIT?"ok":"alert"}`}><strong>{(measureDistance||0)>=LOTTERY_BANK_LIMIT?"Cumple referencia de 200 m":"Dentro del radio de 200 m"}</strong><span>{(measureDistance||0)>=LOTTERY_BANK_LIMIT?`Supera el mínimo por ${Math.floor((measureDistance||0)-LOTTERY_BANK_LIMIT)} m.`:`Faltan aproximadamente ${Math.ceil(LOTTERY_BANK_LIMIT-(measureDistance||0))} m.`}</span></div><MeasureBank label="B" banca={measureB}/><small>Distancia lineal geodésica. La condición legal definitiva depende del tipo de establecimiento, fecha de autorización y excepciones aplicables.</small><button className="full-button" onClick={()=>{setMeasureA(null);setMeasureB(null)}}>Nueva medición</button></aside>}
   <div className="floating-tools" role="toolbar" aria-label="Controles de visualización"><button className={`floating-tool ${panel&&!cleanMode?"primary":""}`} onClick={()=>{setCleanMode(false);setPanel(v=>!v);setViewMenu(false)}} title="Mostrar u ocultar control geográfico" aria-pressed={panel&&!cleanMode}>{panel&&!cleanMode?"‹":"›"}</button><button className={`floating-tool ${viewMenu?"active":""}`} onClick={()=>{setCleanMode(false);setViewMenu(v=>!v)}} title="Opciones de visualización" aria-pressed={viewMenu}>◫</button><button className={`floating-tool ${cleanMode?"active":""}`} onClick={toggleCleanMode} title={cleanMode?"Restaurar interfaz":"Ver mapa sin distracciones"} aria-pressed={cleanMode}>{cleanMode?"↺":"⛶"}</button></div><button className="mobile-filter-button" onClick={()=>{setCleanMode(false);setPanel(true)}}>☰ Filtros y capas</button>
   <aside className={`control-panel ${panel&&!cleanMode?"panel-open mobile-open":"panel-closed"}`}><div className="panel-head"><div><span className="eyebrow">Control geográfico</span><h1>Mapa nacional</h1></div><button className="icon-button" onClick={()=>setPanel(false)}>×</button></div>
    <label className="search-box"><span>⌕</span><input value={query} onChange={e=>{setQuery(e.target.value);setSearchSubmitted(false)}} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();setSearchSubmitted(true);setShowBancas(true);setPanel(false)}}} placeholder="Buscar banca, propietario o ubicación"/>{query&&<button type="button" className="search-clear" onClick={()=>{setQuery("");setSearchSubmitted(false)}} aria-label="Limpiar búsqueda">×</button>}</label>
    <div className="filter-grid"><label><span>Provincia</span><select value={province} onChange={e=>{setProvince(e.target.value);setSearchSubmitted(false)}}>{provinces.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Estatus</span><select value={status} onChange={e=>{setStatus(e.target.value);setSearchSubmitted(false)}}><option>Todos</option><option>Legal</option><option>Ilegal</option><option>Pendiente</option><option>Suspendida</option></select></label><label><span>Riesgo</span><select value={risk} onChange={e=>{setRisk(e.target.value);setSearchSubmitted(false)}}><option>Todos</option><option>Bajo</option><option>Moderado</option><option>Alto</option></select></label></div>
    <div className="layers-title">Capas territoriales</div><Layer title="Bancas de lotería" count={filtered.length} active={showBancas} color="banca" onClick={()=>setShowBancas(v=>!v)}/><Layer title="Centros educativos" count={schools.length} active={showSchools} color="school" onClick={()=>setShowSchools(v=>!v)}/><Layer title="Centros de salud" count={health.length} active={showHealth} color="health" onClick={()=>setShowHealth(v=>!v)}/><Layer title="Destacamentos policiales" count={police.length} active={showPolice} color="police" onClick={()=>setShowPolice(v=>!v)}/>
    <div className="filter-footer"><strong>{filtered.length.toLocaleString("es-DO")} bancas visibles</strong><button onClick={()=>{setQuery("");setSearchSubmitted(false);setProvince(ALL);setStatus(ALL);setRisk(ALL)}}>Limpiar</button></div>
   </aside>
   {panel&&!cleanMode&&<div className="mobile-overlay" onClick={()=>setPanel(false)}/>}
   {viewMenu&&!cleanMode&&<section className="view-menu"><div className="view-menu-head"><div><span className="eyebrow">Visualización</span><strong>Elementos del mapa</strong></div><button onClick={()=>setViewMenu(false)}>×</button></div><ViewToggle label="Bancas" active={showBancas} onClick={()=>setShowBancas(v=>!v)}/><ViewToggle label="Escuelas" active={showSchools} onClick={()=>setShowSchools(v=>!v)}/><ViewToggle label="Centros de salud" active={showHealth} onClick={()=>setShowHealth(v=>!v)}/><ViewToggle label="Destacamentos policiales" active={showPolice} onClick={()=>setShowPolice(v=>!v)}/><ViewToggle label="Líneas de proximidad" active={showLines} onClick={()=>setShowLines(v=>!v)}/><ViewToggle label="Indicadores superiores" active={showStats} onClick={()=>setShowStats(v=>!v)}/><ViewToggle label="Ficha de detalle" active={showDetails} onClick={()=>setShowDetails(v=>!v)}/><ViewToggle label="Estado inferior" active={showStatus} onClick={()=>setShowStatus(v=>!v)}/><ViewToggle label="Panel de control" active={panel} onClick={()=>setPanel(v=>!v)}/><button className="clean-map-button" onClick={toggleCleanMode}>Ver mapa sin distracciones</button></section>} 
   {showStats&&!cleanMode&&<section className="map-stats"><article><span>{hasActiveFilters?"Bancas filtradas":"Total de bancas"}</span><strong>{filteredStats.total.toLocaleString("es-DO")}</strong></article><article><span>Bancas legales</span><strong>{filteredStats.legal.toLocaleString("es-DO")}</strong></article><article><span>Bancas ilegales</span><strong>{filteredStats.ilegal.toLocaleString("es-DO")}</strong></article><article><span>Escuelas cercanas</span><strong>{filteredStats.schools.toLocaleString("es-DO")}</strong></article><article><span>Salud cercana</span><strong>{filteredStats.health.toLocaleString("es-DO")}</strong></article><article><span>Destacamentos cercanos</span><strong>{filteredStats.police.toLocaleString("es-DO")}</strong></article></section>}
   {selected&&showDetails&&!cleanMode&&<Detail title={selected.nombre} code={selected.id} onClose={()=>setSelected(null)}><div className="status-row"><span className={`status-badge ${selected.estatus.toLowerCase()}`}>{selected.estatus}</span><span className={`risk-badge ${selected.riesgo.toLowerCase()}`}>Riesgo {selected.riesgo}</span></div><dl><div><dt>Propietario</dt><dd>{selected.propietario}</dd></div><div><dt>Ubicación</dt><dd>{selected.sector}, {selected.municipio}</dd></div><div><dt>Dirección</dt><dd>{selected.direccion}</dd></div><div><dt>Coordenadas</dt><dd>{selected.lat.toFixed(6)}, {selected.lng.toFixed(6)}</dd></div><div><dt>Origen de ubicación</dt><dd><LocationSource source={selected.locationSource}/></dd></div></dl><RegulatorySummary selected={selected}/><Compliance label="Centro educativo más cercano" name={selected.escuelaCercanaNombre||"No identificado"} meters={selected.escuelaDistanciaM} limit={PROTECTED_PLACE_LIMIT} onClick={()=>openSchool(escuelas.find(x=>x.codigo===selected.escuelaCercanaCodigo))}/><Compliance label="Centro de salud más cercano" name={selected.saludCercana?.nombre||"No identificado"} meters={selected.saludDistanciaM} limit={PROTECTED_PLACE_LIMIT} onClick={()=>openHealth(selected.saludCercana)}/><Compliance label="Cuartel o destacamento más cercano" name={selected.destacamentoCercano?.nombre||"No identificado"} meters={selected.destacamentoDistanciaM} limit={PROTECTED_PLACE_LIMIT} onClick={()=>openPolice(selected.destacamentoCercano)}/><NearbyBanks items={selected.nearbyBancas} onSelect={chooseBanca}/><div className="detail-actions"><button>Ver expediente</button><button className="primary-button">Iniciar inspección</button></div></Detail>}
   {selectedSchool&&showDetails&&!cleanMode&&<Detail title={selectedSchool.nombre} code={`CENTRO ${selectedSchool.codigo}`} onClose={()=>setSelectedSchool(null)}><span className="school-badge">Centro educativo</span><dl><div><dt>Provincia</dt><dd>{selectedSchool.provincia}</dd></div><div><dt>Municipio</dt><dd>{selectedSchool.municipio}</dd></div><div><dt>Nivel</dt><dd>{selectedSchool.nivel}</dd></div><div><dt>Sector</dt><dd>{selectedSchool.sector}</dd></div></dl><Source text={schoolMeta.source}/></Detail>}
   {selectedHealth&&showDetails&&!cleanMode&&<Detail title={selectedHealth.nombre} code={`SALUD ${selectedHealth.id}`} onClose={()=>setSelectedHealth(null)}><span className="health-badge">{selectedHealth.tipo}</span><dl><div><dt>Provincia</dt><dd>{selectedHealth.provincia}</dd></div><div><dt>Municipio</dt><dd>{selectedHealth.municipio}</dd></div><div><dt>Nivel</dt><dd>{selectedHealth.nivel}</dd></div><div><dt>Estado</dt><dd>{selectedHealth.estado}</dd></div><div><dt>Dirección</dt><dd>{selectedHealth.direccion}</dd></div></dl><Source text={healthMeta.source}/></Detail>}{selectedPolice&&showDetails&&!cleanMode&&<Detail title={selectedPolice.nombre} code={`POLICÍA ${selectedPolice.id}`} onClose={()=>setSelectedPolice(null)}><span className="police-badge">{selectedPolice.categoria||"Destacamento policial"}</span><dl><div><dt>Municipio</dt><dd>{selectedPolice.municipio||"No especificado"}</dd></div><div><dt>Dirección</dt><dd>{selectedPolice.direccion}</dd></div><div><dt>Teléfono</dt><dd>{selectedPolice.telefono||"No disponible"}</dd></div><div><dt>Horario</dt><dd>{selectedPolice.horario||"No disponible"}</dd></div><div><dt>Coordenadas</dt><dd>{selectedPolice.lat.toFixed(6)}, {selectedPolice.lng.toFixed(6)}</dd></div></dl><Source text={policeMeta.source}/></Detail>}
   {sim&&showDetails&&!cleanMode&&<Detail title="Análisis del local" code="SIMULADOR TERRITORIAL" onClose={()=>setSim(null)}><div className={`viability ${sim.schoolD>=PROTECTED_PLACE_LIMIT&&sim.healthD>=PROTECTED_PLACE_LIMIT&&sim.policeD>=PROTECTED_PLACE_LIMIT?"ok":"alert"}`}><strong>{sim.schoolD>=PROTECTED_PLACE_LIMIT&&sim.healthD>=PROTECTED_PLACE_LIMIT&&sim.policeD>=PROTECTED_PLACE_LIMIT?"Ubicación preliminarmente viable":"Ubicación no recomendada"}</strong><span>Evaluación automática con las capas disponibles.</span></div><Compliance label="Centro educativo" name={sim.school?.nombre||"No identificado"} meters={sim.schoolD} limit={PROTECTED_PLACE_LIMIT}/><Compliance label="Centro de salud" name={sim.health?.nombre||"No identificado"} meters={sim.healthD} limit={PROTECTED_PLACE_LIMIT}/><Compliance label="Cuartel o destacamento policial" name={sim.police?.nombre||"No identificado"} meters={sim.policeD} limit={PROTECTED_PLACE_LIMIT}/><small className="legal-note">Resultado preliminar. Requiere medición oficial, validación de coordenadas y revisión de la norma aplicable.</small><button className="full-button" onClick={()=>setSimMode(true)}>Analizar otro punto</button></Detail>}
   <nav className="mobile-nav"><button onClick={()=>setPanel(true)}>☰<span>Filtros</span></button><button className={simMode?"active":""} onClick={()=>{setSimMode(v=>!v);closeCards()}}>◎<span>Simular</span></button><button onClick={()=>{setShowSchools(v=>!v)}}>▣<span>Escuelas</span></button><button onClick={()=>setShowHealth(v=>!v)}>✚<span>Salud</span></button><button onClick={()=>setShowPolice(v=>!v)}>◆<span>Policía</span></button></nav>
   {showStatus&&!cleanMode&&<div className="map-status"><span className="pulse"/>Mapa conectado · {filtered.length.toLocaleString("es-DO")} bancas</div>}
  </section>
 </main>
}
function Layer({title,count,active,color,onClick}:{title:string;count:number;active:boolean;color:string;onClick:()=>void}){return <div className="layer-switch"><div><i className={`layer-dot ${color}`}/><strong>{title}</strong><small>{count.toLocaleString("es-DO")} ubicaciones</small></div><button className={active?"active":""} onClick={onClick}><span/></button></div>}
function Detail({title,code,onClose,children}:{title:string;code:string;onClose:()=>void;children:React.ReactNode}){return <aside className="detail-card"><div className="detail-handle"/><div className="detail-top"><div><span className="record-code">{code}</span><h2>{title}</h2></div><button onClick={onClose}>×</button></div>{children}</aside>}
function Compliance({label,name,meters,limit,onClick}:{label:string;name:string;meters:number;limit:number;onClick?:()=>void}){const ok=meters>=limit;const content=<><span>{label}</span><strong>{name}</strong><div className="distance-value">{fmt(meters)}</div><div className={`compliance-result ${ok?"ok":"alert"}`}><b>{ok?"Fuera del radio restringido":"Posible incumplimiento"}</b><em>Referencia activa: mínimo {limit} m lineales</em><small>{ok?`Supera la referencia por ${Math.floor(meters-limit)} m.`:`Faltan aproximadamente ${Math.ceil(limit-meters)} m.`}</small></div>{onClick&&<small className="open-record">Ver información completa →</small>}</>;return onClick?<button type="button" className="proximity-box proximity-link" onClick={onClick}>{content}</button>:<div className="proximity-box">{content}</div>}
function DistanceInfo({label,name,meters}:{label:string;name:string;meters:number}){return <div className="proximity-box"><span>{label}</span><strong>{name}</strong><div className="distance-value">{fmt(meters)}</div><small>Distancia geodésica en línea recta desde la ubicación seleccionada.</small></div>}

function MeasureBank({label,banca}:{label:"A"|"B";banca:Banca}){return <div className="measure-bank rich"><i className={label==="A"?"point-a":"point-b"}>{label}</i><div><strong>{banca.nombre}</strong><span>{banca.id} · {banca.estatus} · Riesgo {banca.riesgo}</span><small>{banca.propietario}</small><small>{banca.direccion}, {banca.municipio}</small></div></div>}
function RegulatorySummary({selected}:{selected:SelectedBanca}){const alerts=[selected.escuelaDistanciaM,selected.saludDistanciaM,selected.destacamentoDistanciaM].filter(x=>x<PROTECTED_PLACE_LIMIT).length+selected.nearbyBancas.length;return <section className={`regulatory-summary ${alerts?"alert":"ok"}`}><span>Evaluación geoespacial · Art. 26</span><strong>{alerts?`${alerts} alerta${alerts===1?"":"s"} territorial${alerts===1?"":"es"}`:"Sin alertas en las capas disponibles"}</strong><small>Referencia: 500 m respecto de lugares protegidos y 200 m entre bancas de lotería. Una banca legal preexistente puede estar alcanzada por la excepción del Art. 178; hace falta la fecha y resolución de autorización para decidirlo.</small></section>}
function NearbyBanks({items,onSelect}:{items:{banca:Banca;distanceM:number}[];onSelect:(b:Banca)=>void}){return <section className={`nearby-banks ${items.length?"alert":"ok"}`}><div className="nearby-head"><div><span>Bancas dentro de 200 m</span><strong>{items.length?`${items.length} encontrada${items.length===1?"":"s"}`:"Ninguna encontrada"}</strong></div><b>{items.length}</b></div>{items.slice(0,12).map(x=><button type="button" className="nearby-item nearby-link" key={x.banca.id} onClick={()=>onSelect(x.banca)}><div><strong>{x.banca.nombre}</strong><span>{x.banca.id} · {x.banca.estatus}</span></div><em>{fmt(x.distanceM)}</em></button>)}{items.length>12&&<small>Se muestran 12 de {items.length}. Todas están conectadas por línea en el mapa.</small>}</section>}
function ViewToggle({label,active,onClick}:{label:string;active:boolean;onClick:()=>void}){return <button className="view-toggle" onClick={onClick}><span>{label}</span><i className={active?"active":""}><b/></i></button>}
function Source({text}:{text:string}){return <div className="proximity-box"><span>Fuente de datos</span><strong>{text}</strong><small>Registro geográfico suministrado e integrado a la plataforma.</small></div>}

function LocationSource({source}:{source:Banca["locationSource"]}){const labels={original:"Coordenada original",direccion:"Corregida por dirección",sector:"Aproximada por sector",municipio:"Aproximada por municipio",provincia:"Aproximada por provincia",pendiente:"Pendiente de validación"};return <span className={`location-source ${source||"original"}`}>{labels[source||"original"]}</span>}
